Feature/crud competition service back 27
InAI-Inteli/inai-web-app-competition-service pull request #1
Opened 2023-11-09 11:19 UTC by KalebIsaias

Configuração inicial do repositório.

2023-11-09 15:48 UTC, KalebIsaias commented
O nome dessa branch é feature/crud-competition-service-BACK-27 em referência ao card 27 do jira. Criei essa branch a partir desse card, porém não utilizei ess branch para fazer o crud e sim para fazer a configuração inicial do microsserviço. 

Criei uma nova branch chamada feature/crud-competicao. A base dessa branch é a branch feature/crud-competition-service-BACK-27.

Paia

![PuppetAwkwardGIF](https://github.com/InAI-Inteli/inai-web-app-competition-service/assets/124165852/74153524-1696-4c88-b733-829d95b24bad)

2023-11-09 21:03 UTC, Vitto-Mazeto requested changes
Po mano, base boa, só fiz alguns comentários e precisa mudar os curos

2023-11-09 21:03 UTC, Vitto-Mazeto commented on src/WebApiCompetitionService/Applitcation/Controllers/EquipesUsuariosController.cs
> +    [Route("api/[controller]")]
Po, acho que no nosso padrão seria sem o api, só o controller, confere @VictorGM01 ? Ou coloca API? Se for colocar mudo no outro

2023-11-09 21:03 UTC, Vitto-Mazeto commented on src/WebApiCompetitionService/Domain/Entities/Inscricoes.cs
> +        public string? Curos { get; set; }
Oq eh Curos?

2023-11-09 21:03 UTC, Vitto-Mazeto commented on src/WebApiCompetitionService/Infra/Data/Mappings/InscricoesConfiguration.cs
> +            builder.Property(e => e.Curos)
Ahh, acho que eh algo no proprio banco, confere @Anag0es @VictorGM01 ?

Talvez tenha que modificar o Curos lá para cursos, ai ajeita por aqui

2023-11-09 21:27 UTC, KalebIsaias commented
> Po mano, base boa, só fiz alguns comentários e precisa mudar os curos

![image](https://github.com/InAI-Inteli/inai-web-app-competition-service/assets/124165852/85e77709-3f92-4a5a-a816-23eeeafb9fa8)

Acredito que seja um erro no banco de dados mesmos.
@Anag0es confirma?

2023-11-09 21:44 UTC, Anag0es commented
Arrumado!
Falhou o português, i'm sorry

Em qui., 9 de nov. de 2023 às 18:28, Kaleb ***@***.***>
escreveu:

> Po mano, base boa, só fiz alguns comentários e precisa mudar os curos
>
> [image: image]
> <https://user-images.githubusercontent.com/124165852/281874440-85e77709-3f92-4a5a-a816-23eeeafb9fa8.png>
>
> Acredito que seja um erro no banco de dados mesmos.
> @Anag0es <https://github.com/Anag0es> confirma?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/InAI-Inteli/inai-web-app-competition-service/pull/1#issuecomment-1804711305>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU7OJOK7UYWPC2BMERZ75FTYDVDGVAVCNFSM6AAAAAA7EMM2XKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBUG4YTCMZQGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-11-10 17:49 UTC, KalebIsaias commented
Fiz as alterações dos 'Curos' na branch seguinte.

2023-11-10 18:09 UTC, KalebIsaias commented on src/WebApiCompetitionService/Applitcation/Controllers/EquipesUsuariosController.cs
> +    [Route("api/[controller]")]
Vi que no outro microsserviço que é `[Route("[controller]")]`
Corrigi na branch feature/crud-competicao

2023-11-11 18:39 UTC, Vitto-Mazeto approved these changes
Aprovado!!!!!!!!!

2023-11-17 23:53 UTC, VictorGM01 approved these changes

2023-11-17 23:54 UTC, merged